In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor([[[[1111, 1112, 1113, 1114],
                    [1121, 1122, 1123, 1124],
                    [1131, 1132, 1133, 1134]],

                   [[1211, 1212, 1213, 1214],
                    [1221, 1222, 1223, 1224],
                    [1231, 1232, 1233, 1234]],

                   [[1311, 1312, 1313, 1314],
                    [1321, 1322, 1323, 1324],
                    [1331, 1332, 1333, 1334]]],

                  [[[2111, 2112, 2113, 2114],
                    [2121, 2122, 2123, 2124],
                    [2131, 2132, 2133, 2134]],

                   [[2211, 2212, 2213, 2214],
                    [2221, 2222, 2223, 2224],
                    [2231, 2232, 2233, 2234]],

                   [[2311, 2312, 2313, 2314],
                    [2321, 2322, 2323, 2324],
                    [2331, 2332, 2333, 2334]]]], dtype=torch.int32)


print(x)

xin = x.clone()

tensor([[[[1111, 1112, 1113, 1114],
          [1121, 1122, 1123, 1124],
          [1131, 1132, 1133, 1134]],

         [[1211, 1212, 1213, 1214],
          [1221, 1222, 1223, 1224],
          [1231, 1232, 1233, 1234]],

         [[1311, 1312, 1313, 1314],
          [1321, 1322, 1323, 1324],
          [1331, 1332, 1333, 1334]]],


        [[[2111, 2112, 2113, 2114],
          [2121, 2122, 2123, 2124],
          [2131, 2132, 2133, 2134]],

         [[2211, 2212, 2213, 2214],
          [2221, 2222, 2223, 2224],
          [2231, 2232, 2233, 2234]],

         [[2311, 2312, 2313, 2314],
          [2321, 2322, 2323, 2324],
          [2331, 2332, 2333, 2334]]]], dtype=torch.int32)


---

x[B,C,H,W] -> x1[B,W,C,H]


batch不变，每张图片变为高度为C，宽度为H，通道数为W

---

In [3]:
x1 = x.permute(0, 3, 1, 2)

print(x1)
print(x1.shape)

tensor([[[[1111, 1121, 1131],
          [1211, 1221, 1231],
          [1311, 1321, 1331]],

         [[1112, 1122, 1132],
          [1212, 1222, 1232],
          [1312, 1322, 1332]],

         [[1113, 1123, 1133],
          [1213, 1223, 1233],
          [1313, 1323, 1333]],

         [[1114, 1124, 1134],
          [1214, 1224, 1234],
          [1314, 1324, 1334]]],


        [[[2111, 2121, 2131],
          [2211, 2221, 2231],
          [2311, 2321, 2331]],

         [[2112, 2122, 2132],
          [2212, 2222, 2232],
          [2312, 2322, 2332]],

         [[2113, 2123, 2133],
          [2213, 2223, 2233],
          [2313, 2323, 2333]],

         [[2114, 2124, 2134],
          [2214, 2224, 2234],
          [2314, 2324, 2334]]]], dtype=torch.int32)
torch.Size([2, 4, 3, 3])


---
x[B,C,H,W] -> x1[B,H,C,W]

batch与图片宽度不变，每张图片高度变为C，通道数变为H

---

In [4]:
x2 = x.permute(0, 2, 1, 3)

print(x2)
print(x2.shape)

tensor([[[[1111, 1112, 1113, 1114],
          [1211, 1212, 1213, 1214],
          [1311, 1312, 1313, 1314]],

         [[1121, 1122, 1123, 1124],
          [1221, 1222, 1223, 1224],
          [1321, 1322, 1323, 1324]],

         [[1131, 1132, 1133, 1134],
          [1231, 1232, 1233, 1234],
          [1331, 1332, 1333, 1334]]],


        [[[2111, 2112, 2113, 2114],
          [2211, 2212, 2213, 2214],
          [2311, 2312, 2313, 2314]],

         [[2121, 2122, 2123, 2124],
          [2221, 2222, 2223, 2224],
          [2321, 2322, 2323, 2324]],

         [[2131, 2132, 2133, 2134],
          [2231, 2232, 2233, 2234],
          [2331, 2332, 2333, 2334]]]], dtype=torch.int32)
torch.Size([2, 3, 3, 4])


---
x1[B,C',H',W']->x1'[B*C',H',W']

batch改变，从二维矩阵变为一维向量

改变前：
B个batch，每张图片高为H',宽为W',通道为C'

改变后：
B*C'个batch，每个向量长为W',通道数为H'

---

In [5]:
N1, W1, C1, H1 = x1.shape
x1 = x1.contiguous().view(N1 * W1, C1, H1)
print(x1)

tensor([[[1111, 1121, 1131],
         [1211, 1221, 1231],
         [1311, 1321, 1331]],

        [[1112, 1122, 1132],
         [1212, 1222, 1232],
         [1312, 1322, 1332]],

        [[1113, 1123, 1133],
         [1213, 1223, 1233],
         [1313, 1323, 1333]],

        [[1114, 1124, 1134],
         [1214, 1224, 1234],
         [1314, 1324, 1334]],

        [[2111, 2121, 2131],
         [2211, 2221, 2231],
         [2311, 2321, 2331]],

        [[2112, 2122, 2132],
         [2212, 2222, 2232],
         [2312, 2322, 2332]],

        [[2113, 2123, 2133],
         [2213, 2223, 2233],
         [2313, 2323, 2333]],

        [[2114, 2124, 2134],
         [2214, 2224, 2234],
         [2314, 2324, 2334]]], dtype=torch.int32)


---

同x1的变化

---

In [6]:
N2, W2, C2, H2 = x2.shape
x2 = x2.contiguous().view(N2 * W2, C2, H2)
print(x2)

tensor([[[1111, 1112, 1113, 1114],
         [1211, 1212, 1213, 1214],
         [1311, 1312, 1313, 1314]],

        [[1121, 1122, 1123, 1124],
         [1221, 1222, 1223, 1224],
         [1321, 1322, 1323, 1324]],

        [[1131, 1132, 1133, 1134],
         [1231, 1232, 1233, 1234],
         [1331, 1332, 1333, 1334]],

        [[2111, 2112, 2113, 2114],
         [2211, 2212, 2213, 2214],
         [2311, 2312, 2313, 2314]],

        [[2121, 2122, 2123, 2124],
         [2221, 2222, 2223, 2224],
         [2321, 2322, 2323, 2324]],

        [[2131, 2132, 2133, 2134],
         [2231, 2232, 2233, 2234],
         [2331, 2332, 2333, 2334]]], dtype=torch.int32)


In [7]:
print("x1:",x1.shape)
print("x2:",x2.shape)

x1: torch.Size([8, 3, 3])
x2: torch.Size([6, 3, 4])


In [8]:
qkv = x1

In [10]:
qkv_reshape = qkv.reshape(
    8,
    1,
    3,
    3
)

In [12]:
print(qkv_reshape.shape)
print(qkv_reshape)

torch.Size([8, 1, 3, 3])
tensor([[[[1111, 1121, 1131],
          [1211, 1221, 1231],
          [1311, 1321, 1331]]],


        [[[1112, 1122, 1132],
          [1212, 1222, 1232],
          [1312, 1322, 1332]]],


        [[[1113, 1123, 1133],
          [1213, 1223, 1233],
          [1313, 1323, 1333]]],


        [[[1114, 1124, 1134],
          [1214, 1224, 1234],
          [1314, 1324, 1334]]],


        [[[2111, 2121, 2131],
          [2211, 2221, 2231],
          [2311, 2321, 2331]]],


        [[[2112, 2122, 2132],
          [2212, 2222, 2232],
          [2312, 2322, 2332]]],


        [[[2113, 2123, 2133],
          [2213, 2223, 2233],
          [2313, 2323, 2333]]],


        [[[2114, 2124, 2134],
          [2214, 2224, 2234],
          [2314, 2324, 2334]]]], dtype=torch.int32)


In [13]:
split_sizes = [
    1,   # q
    1,   # k
    1         # v
]

q, k, v = torch.split(
    qkv_reshape,
    split_sizes,
    dim=2
)
print(q)
print(k)
print(v)

tensor([[[[1111, 1121, 1131]]],


        [[[1112, 1122, 1132]]],


        [[[1113, 1123, 1133]]],


        [[[1114, 1124, 1134]]],


        [[[2111, 2121, 2131]]],


        [[[2112, 2122, 2132]]],


        [[[2113, 2123, 2133]]],


        [[[2114, 2124, 2134]]]], dtype=torch.int32)
tensor([[[[1211, 1221, 1231]]],


        [[[1212, 1222, 1232]]],


        [[[1213, 1223, 1233]]],


        [[[1214, 1224, 1234]]],


        [[[2211, 2221, 2231]]],


        [[[2212, 2222, 2232]]],


        [[[2213, 2223, 2233]]],


        [[[2214, 2224, 2234]]]], dtype=torch.int32)
tensor([[[[1311, 1321, 1331]]],


        [[[1312, 1322, 1332]]],


        [[[1313, 1323, 1333]]],


        [[[1314, 1324, 1334]]],


        [[[2311, 2321, 2331]]],


        [[[2312, 2322, 2332]]],


        [[[2313, 2323, 2333]]],


        [[[2314, 2324, 2334]]]], dtype=torch.int32)
